<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Администрирование'=>'Ma‘muriyat',
    'Пользователь'=>'Foydalanuvchi',
    'Создать пользователь'=>'Foydalanuvchi yaratish',
    'Имя пользователя'=>'Foydalanuvchi nomi',
    'Пароль'=>'Parol',
    'Повторите пароль'=>'Parolni qayta kiriting',
    'Дата Регистрации'=>'Ro‘yxatga olingan sana',
    'Дата обновления'=>'Yangilanish sanasi',
    'Профили'=>'Profillar',
    'Группа'=>'Guruh',
    'Создать группа'=>'Guruh yarating',
    'Организации'=>'Tashkilotlar',
    'Права доступа'=>'Kirish huquqlari',
    'Области'=>'Hududlar',
    'Обращения'=>'Apellyatsiya',
    'Новые обращения'=>'Yangi Apellyatsiyalar',
    'Обращения в обработке'=>'Ishlash jarayonida',
    'Архив обращений'=>'Apellyatsiyalar arxivi',
    'Создать обращение'=>'Apellyatsiya yarating',
    'Жертвы'=>'Qurbonlar',
    'Правонарушители'=>'Huquqbuzarlar',
    'Дата обращения'=>'Apellyatsiya berilgan sana',
    'Тип правонарушения'=>'Huquqbuzarlik turi',
    'Ответственный'=>'Yuklatilgan',
    'Cтрана'=>'Mamlakat',
    'Регион'=>'Mintaqa',
    'Район'=>'Tuman',
    'Статус'=>'Holat',
    'Фамилия латинская'=>'Familiyasi lotin',
    'Имя латинская'=>'Ismi Lotin',
    'Отчество латинская'=>'Otasining ismi Lotin',
    'Фамилия Узбек'=>'Familiyasi o‘zbek',
    'Имя Узбек'=>'Ismi o‘zbek',
    'Отчество Узбек'=>'Otasining ismi o‘zbek',
    'Гражданство'=>'Fuqarolik',
    'Семейное положение'=>'Oilaviy ahvol',
    'Пол'=>'Jinsi',
    'Пасспорт'=>'Pasport',
    'Фамилия'=>'Familiya',
    'Имя'=>'Ism',
    'Отчество'=>'Otasining ismi',
    'День рождения'=>'Tug‘ilgan kun',
    'Место рождения'=>'Tug‘ilgan joyi',
    'Текущая страна'=>'Hozirgi mamlakat',
    'Текущий регион'=>'Hozirgi Viloyat',
    'Текущий район'=>'Hozirgi tuman',
    'Текущий полный адрес'=>'Joriy to‘liq manzil',
    'Страна регистрации'=>'Ro‘yxatdan o‘tgan mamlakat',
    'Регион регистрации'=>'Ro‘yxatdan o‘tish hududi',
    'Регистрационный округ'=>'Ro‘yxatga olish okrugi',
    'Полный адрес регистрации'=>'To‘liq ro‘yxatdan o‘tish manzili',
    'Описание'=>'Tavsif',
    'Название файла'=>'Fayl nomi',
    'Размер'=>'Hajmi',
    'Название'=>'Ism',
    'ПИНФЛ'=>'PINFL',
    'Серия'=>'Seriya',
    'Номер'=>'Raqam',
    'Дата выдачи паспорта'=>'Pasport berilgan sana',
    'Дата истечения'=>'tugash muddati',
    'Место выдачи паспорта'=>'Pasport berilgan joy',
    'Шаг.'=>'Qadam.',
    'Прикрепленные документы'=>'Ilova qilingan hujjatlar',
    'История'=>'Hikoya',
    'Ничего не найдено'=>'Hech narsa topilmadi',
    'Тип предоставляемой помощи'=>'Taqdim etilgan yordam turi',
    'Предоставление помощи'=>'Yordam berish',
    'Вы уверены, что хотите удалить этот элемент?'=>'Haqiqatan ham bu elementni oʻchirib tashlamoqchimisiz?',
    'Создать организацию'=>'Tashkilot yarating',
    'Сохранять'=>'Saqlamoq',
    'Сброс'=>'Qayta o‘rnatish',
    'Обновить'=>'Tahrirlash',
    'Удалить'=>'Oʻchirish',
    'Информация о заявке' => 'Apellyatsiya haqida ma‘lumot',
    'Информация о жертве' => 'Jabrlanuvchi haqida ma‘lumot',
    'Информация о правонарушителе' => 'Huquqbuzar haqida ma‘lumot',
    'Дополнения' => 'Qo‘shimchalar',
    'Дальше' => 'Davom etish',
];