<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Администрирование'=>'Administration',
    'Пользователь'=>'User',
    'Создать пользователь'=>'Create an user',
    'Имя пользователя'=>'Username',
    'Пароль'=>'Password',
    'Повторите пароль'=>'Repeat password',
    'Дата Регистрации'=>'Date of Registration',
    'Дата обновления'=>'Date of updated',
    'Профили'=>'Profiles',
    'Группа'=>'Group',
    'Создать группа'=>'Create an group',
    'Организации'=>'Organizations',
    'Права доступа'=>'Access right',
    'Области'=>'Areas',
    'Обращения'=>'Appeals',
    'Новые обращения'=>'New appeals',
    'Обращения в обработке'=>'Appeals in processing',
    'Архив обращений'=>'Appeals archive',
    'Создать обращение'=>'Create an appeal',
    'Жертвы'=>'Victims',
    'Правонарушители'=>'Offenders',
    'Дата обращения'=>'date of the appeal',
    'Тип правонарушения'=>'Type of offense',
    'Ответственный'=>'Responsible',
    'Cтрана'=>'Country',
    'Регион'=>'Region',
    'Район'=>'District',
    'Статус'=>'Status',
    'Фамилия латинская'=>'Lastname Latin',
    'Имя латинская'=>'Firstname Latin',
    'Отчество латинская'=>'Latin Surname',
    'Фамилия Узбек'=>'Lastname Uzbek',
    'Имя Узбек'=>'Firstname Uzbek',
    'Отчество Узбек'=>'Surname Uzbek',
    'Гражданство'=>'Citizenship',
    'Семейное положение'=>'Family status',
    'Пол'=>'Gender',
    'Пасспорт'=>'Passport',
    'Фамилия'=>'Lastname',
    'Имя'=>'Firstname',
    'Отчество'=>'Surname',
    'День рождения'=>'Birthday',
    'Место рождения'=>'Place of Birth',
    'Текущая страна'=>'Current country',
    'Текущий регион'=>'Current region',
    'Текущий район'=>'Current area',
    'Текущий полный адрес'=>'Current full address',
    'Страна регистрации'=>'Country of registration',
    'Регион регистрации'=>'Registration region',
    'Регистрационный округ'=>'Registration district',
    'Полный адрес регистрации'=>'Full registration address',
    'Описание'=>'Description',
    'Название файла'=>'File name',
    'Размер'=>'Size',
    'Название'=>'Name',
    'ПИНФЛ'=>'PINFL',
    'Серия'=>'Series',
    'Номер'=>'Number',
    'Дата выдачи паспорта'=>'Passport issue date',
    'Дата истечения'=>'Expiration date',
    'Место выдачи паспорта'=>'Place of issue of the passport',
    'Шаг.'=>'Step. ',
    'Прикрепленные документы'=>'Attached Documents',
    'История'=>'History',
    'Ничего не найдено'=>'No Items Found',
    'Тип предоставляемой помощи'=>'Type of assistance provided',
    'Предоставление помощи'=>'Assistance provided',
    'Вы уверены, что хотите удалить этот элемент?'=>'Are you sure you want to delete this item?',
    'Создать организацию'=>'Create Organization',
    'Сохранять'=>'Save',
    'Сброс'=>'Reset',
    'Обновить'=>'Update',
    'Удалить'=>'Delete',
    'Информация о заявке' => 'Application Information',
    'Информация о жертве' => 'Information about the victim',
    'Информация о правонарушителе' => 'Information about the offender',
    'Дополнения' => 'Additions',
    'Дальше' => 'Next',

];